### ISSUE TITLE
Using enter key instead of mouse click causes modal to open & immediately close

### ISSUE THREAD

**Issue by marcysutton** [awkward/backbone.modal#23]
When I use the keyboard to trigger a click instead of a mouse, the modal window opens and then immediately closes. This happens in your examples and in my local build. 

Here is an animated gif of first using the mouse and then a few keypresses:

![backbonemodal-keyboard-bug](https://f.cloud.github.com/assets/1045233/1835894/40de6110-73f8-11e3-8856-9970aea7e788.gif)

**Comment by Lemmmy** [comment]
This appears to still be an issue in 1.1.6. Are there any workarounds for this?
Specifically, if the modal is opened in a 'keydown' event, it will close itself when the user lifts the enter key, as it triggers the modal's 'keyup' event.
