### ISSUE TITLE
Any call to modal.destroy() throws a jQuery addClass error

### ISSUE THREAD

**Issue by gauthamchandra** [awkward/backbone.modal#54]
It seems that when using Marionette and Backbone.modal, any call to modal.destroy() whether from the modalsContainer (i.e App.modalsContainer.destroy()) or from within the view (i.e. this.destroy) uses a reference to this.modalEl instead of this.$el.

This causes an undefined reference in a jQuery addClass statement to fail with:
```javascript
Uncaught TypeError: Cannot read property 'addClass' of undefined
```

inside the Modal.prototype.destroy function, particularly with this line: 
```javascript
this.modalEl.addClass("" + this.prefix + "-modal--destroy");
```

I currently just run this in the onDestroy() event handler in the view to get around it but this should be fixed:
```javascript
this.modalEl = this.$el 
```

**Comment by davidvanleeuwen** [comment]
`this.modalEl` is actually a wrapped element around the template and is generated on render. Did you overwrite the `render` method in your view? That would explain it, because I can't reproduce this.

**Comment by gauthamchandra** [comment]
Ah yes, I was overwriting render. That explains it. Thanks!
