### ISSUE TITLE
Refresh (re-render) step view

### ISSUE THREAD

**Issue by edravis** [awkward/backbone.modal#56]
I'm looking for that and I don't find it, it is implemented in anyway? It'd be an awesome feature!

**Comment by davidvanleeuwen** [comment]
You can call `.render()` with the options for the second step, e.g.: `modalView.render({name: 'tab2'})` like in the example. Hope that helps.

**Comment by jeff-h** [comment]
For anyone finding this issue, I found that the above method causes the entire modal to redraw with its fade-in animation.

Assuming you created the modal with one or more backbone views via the Modal `views` object/array, I discovered you can access the view shown inside the modal and re-render it as follows:

```js
modalView.currentView.render()
```

This re-renders the modal's content, without redrawing the entire modal, thus no animation or flashing.
