### ISSUE TITLE
template attribute can not be a string like in Marionette.

### ISSUE THREAD

**Issue by coulix** [awkward/backbone.modal#58]
In the example it uses `template: _.template()`

    var Modal1 = Backbone.Modal.extend({
            template: _.template($('#modal-template1').html()),

It is not possible to refer to a string instead of a method:

        var Modal1 = Backbone.Modal.extend({
            template: "#modal-template1",

http://marionettejs.com/docs/marionette.view.html

Looking at the backbone.modal code we see that it calls ` this.modalEl.html(this.template(data));` and fails if template is a string.

       Modal.prototype.render = function(options) {
           var data, _ref;
            data = this.serializeData();
              if (!options || _.isEmpty(options)) {
                options = 0;
              }
              this.$el.addClass("" + this.prefix + "-wrapper");
              this.modalEl = Backbone.$('<div />').addClass("" + this.prefix + "-modal");
              if (this.template) {
                      this.modalEl.html(this.template(data));
              }

In Marionette they use something like:

    var templateFunc;
        if (typeof template === 'function') {
         templateFunc = template;
        } else {
          templateFunc = Marionette.TemplateCache.get(template);
        }

See https://github.com/marionettejs/backbone.marionette/blob/9bdb9e61e149512bed829c9e8c839470df992978/src/renderer.js

I will try to make it work in a fork and submit a PR.

**Comment by davidvanleeuwen** [comment]
Thanks for pointing this out, I implemented a simple variant that accomplishes the same thing.
