### ISSUE TITLE
click-drag element in modal outside the modal region and release click causes modal to close 

### ISSUE THREAD

**Issue by justin-hackin** [awkward/backbone.modal#60]
It seems you trigger the close of modal on mouseup on dark overlay, wheras I should have to click down and up on the dark part to have it close.  This is particularly troublesome for a dialog I have with sliders at the very edges of the dialog.

**Comment by ericmcdaniel** [comment]
I am having this issue as well.

**Comment by justin-hackin** [comment]
If you want to fix this issue, you can modify the backbone.modal.coffee file as such:
In rendererCompleted , replace the line with  Backbone.$('body').on('click.... with this:
```
Backbone.$('body').on('mousedown.check', (e)->
          if  Backbone.$(e.target).hasClass("#{self.prefix}-wrapper")
            Backbone.$('body').on('mouseup.check', 
              self.clickOutside(e)
            )
        )
```
and in clickOutside, add another line as follows:
```
Backbone.$('body').off('mouseup.check')
```

**Comment by davidvanleeuwen** [comment]
Doing a simple `mouseup` would fix this problem as well right?

**Comment by davidvanleeuwen** [comment]
Let me know if that works for you.
