### ISSUE TITLE
Keys in textarea element closes modal

### ISSUE THREAD

**Issue by RusAlex** [awkward/backbone.modal#67]
When you add textarea to your modal, and will try to type something in it, and desire to add new line by pressing enter. Your modal closes. As it listens $('body').on('keyup')  event. Suppose keys in textarea must be ignored.

**Comment by RusAlex** [comment]
Thank you very much.

**Comment by davidvanleeuwen** [comment]
Thanks for letting me know :+1:

**Comment by alfredo-cp** [comment]
@davidvanleeuwen I think the fix should consider when the user press enter in an input field

```javascript
 if (Backbone.$(e.target).is('textarea, input')) {
  return;
}
```

^ This does work for me.

And also there's another issue when the user press enter inside an input in a form inside the modal (when enter is pressed in an input inside a form it is submitted by "clicking" the default submit button) The click event fires BUT the target was not on an element outside the modal so ```this.outsideElement``` is not defined. I have fixed it with this:

```javascript
Modal.prototype.clickOutside = function(e) {
  if (this.outsideElement.hasClass("" + this.prefix + "-wrapper") && this.active) {
  if (!!this.outsideElement && this.outsideElement.hasClass("" + this.prefix + "-wrapper") && this.active) {
    return this.triggerCancel();
  }
};
```

**Comment by davidvanleeuwen** [comment]
I don't think it makes sense to use it on an input though, as default behaviour is to 'submit' something when hitting enter.
