### ISSUE TITLE
Tester takes place in the flow

### ISSUE THREAD

**Issue by LeBenLeBen** [awkward/backbone.modal#69]
My modal have some custom styling to make it fixed and centered in the viewport:

```
  .bbm-wrapper {
    display: table;
    width: 100%;
    height: 100%;

    position: fixed;
    top: 0;
    right: 0;
    bottom: 0;
    left: 0;
    z-index: 10;

    text-align: center;
  }

    .bbm-modal {
      display: table-cell;
      vertical-align: middle;
    }
```

It works great, however, the <tester> element you create gets a relative position and this make it takes spaces in the flow with my styling (in Firefox & IE at least, doesn’t seems to happen in Chrome).

I’ve made some tests and using an absolute position seems to fix the problem without breaking anything apparently.

Would it be possible for you to use an absolute positioning on the <tester> element? You probably have more examples to test with to be sure it still works in any case.

Thanks!

**Comment by jimf** [comment]
Closing due to age, but feel free to reopen.
