### ISSUE TITLE
onShow is called twice

### ISSUE THREAD

**Issue by davidvanleeuwen** [awkward/backbone.modal#75]
https://twitter.com/drwxrxrx/status/591381316991524864

**Comment by alxndr** [comment]
screenshot of putting a `console.trace()` in the onShow of a Backbone.Modal, which gets called twice when showing the instance in something using `regionClass: Backbone.Marionette.Modals`:

![the screenshot](https://pbs.twimg.com/media/CDUCLIiWIAAl4Rp.png)

**Comment by alxndr** [comment]
:+1: :100:

**Comment by lachose1** [comment]
Is it possible this issue is still there, I am experiencing the same problem (Using backbone modal 1.1.5, backbone 1.2.0 and backbone.marionette 2.4.1)
![capture](https://cloud.githubusercontent.com/assets/610170/7946352/251395c6-0944-11e5-8dec-5573ca57b9d0.PNG)
.
