### ISSUE TITLE
Modal scrolling issue

### ISSUE THREAD

**Issue by davidvanleeuwen** [awkward/backbone.modal#77]
https://github.com/awkward/backbone.modal/pull/42#issuecomment-99619218

**Comment by davidvanleeuwen** [comment]
Thanks @dcalhoun, I tried to reproduce this on a simulator before, now on a real iPad. I know what is going wrong now :+1:

**Comment by dcalhoun** [comment]
No problem. I'd also say be aware of the limitations of controlling `body` scroll and virtual keyboard issues with fixed position elements on touch devices. Bootstrap explains some of them in [their documentation](http://getbootstrap.com/getting-started/#support-fixed-position-keyboards). There are definitely items BBM could improve upon, but some items do seem to just be impossible on touch devices.

**Comment by davidvanleeuwen** [comment]
True, some things haven't been touched for a while in the codebase. If it works, don't fix it, right? :smile: 

It seems to be webkit issue actually:
* https://bugs.webkit.org/show_bug.cgi?id=119839
* https://github.com/scottjehl/Device-Bugs/issues/14#issuecomment-98007641

Can't seem to fix it though, I'm still trying.

**Comment by davidvanleeuwen** [comment]
Apparently `-webkit-animation-fill-mode` screws up the click events on mobile safari.
