### ISSUE TITLE
Applying JQuery plugins globally

### ISSUE THREAD

**Issue by xkill-9** [awkward/backbone.modal#87]
I'm trying to apply JQuery plugins to all the instances of Backbone.Modal in my application, with Marionette views i can do this with:

```
 _.extend(Marionette.View.prototype, {
    onDomRefresh: ->
          # Apply your plugin here
```

But i can't get the same results extending the `render` method or creating an `onRender` method in Backbone.Modal.prototype.

I'm i missing something?

**Comment by jimf** [comment]
Closing due to age, but feel free to reopen if you still need assistance. If so, more details would be good, as I see no reason why what I think you're trying to do shouldn't work.
