### ISSUE TITLE
re-render view without "show" animation?

### ISSUE THREAD

**Issue by jeff-h** [awkward/backbone.modal#95]
First off — thanks for your awesome work on this! Loving it.

I'm doing a simple user login form in my modal. If auth fails, I want to shake the modal, and show some error messages at the top of the form. I was thinking of doing this in the data passed into the modal's view template, but when I call `.render()` on the modal, it does the fade-in animation again, so it feels like a whole new modal.

Is there any way to refresh the contents of the modal without any animation?

I've noticed the tab example, where I can define an area inside my modal view for other view(s) — that feels a little more complex to me for my use-case (where I only really need one view), but is that the answer I'm looking for?

**Comment by jeff-h** [comment]
I ended up making this work quite nicely based on the tab example, but with only one "subview".

Assuming you created the modal with one or more backbone views via the Modal `views` object/array, I discovered you can access the view shown inside the modal and re-render it as follows:

```js
modalView.currentView.render()
```

This re-renders the modal's content, without redrawing the entire modal, thus no animation or flashing.

**Comment by amenadiel** [comment]
@jeff-h from what I can see, child views do not have a render method. At least not in current version.
