### ISSUE TITLE
Dynamic Templates for modal

### ISSUE THREAD

**Issue by wkaskie** [awkward/backbone.modal#98]
Would like to see a way to pass the template to the modal view like;

template = "<div>TEST</div>";
var modalView = new Backbone.Modal.extend({
    cancelEl: ".close-button"
};

$('body').html(modalView.render({template:template}).el);

//OR

modalView.template = template;
$('body').html(modalView.render().el);

**Comment by jimf** [comment]
Closing. The former should be doable by extending `Backbone.Modal` and overriding `render`, while the latter should work just fine as is.
