### ISSUE TITLE
Active maintainer

### ISSUE THREAD

**Issue by jimf** [awkward/backbone.modal#99]
Howdy! I'm just opening this issue in response to the [call for active maintainers](https://github.com/awkward/backbone.modal/commit/c76eb6eb4f4e0a172b45b140c426ce538bebf865). I use this library in a number of production applications and would gladly take up the reins.

**Comment by davidvanleeuwen** [comment]
@jimf Awesome! Could you sent me a message on twitter or email david@awkward.co ?

**Comment by jimf** [comment]
Closing, though I'm (currently) not an npm collaborator.
